#pragma once

#include "global.h"

//-----------------------------------------------------------------------------
//
// Leaf node net object types
// N.B. If you add to this list you must also add in cAppPacketStats::Interpret_Type.
//
enum
{
	//
	// S->C
	//	
	APPPACKETTYPE_UNKNOWN,
	APPPACKETTYPE_SIMPLE,
	APPPACKETTYPE_SOLDIER,
	APPPACKETTYPE_VEHICLE,
	APPPACKETTYPE_TURRET,
	APPPACKETTYPE_BUILDING,
	APPPACKETTYPE_PLAYER,
	APPPACKETTYPE_TEAM,
	APPPACKETTYPE_GAMEOPTIONSEVENT,
	APPPACKETTYPE_PLAYERKILLEVENT,
	APPPACKETTYPE_PURCHASERESPONSEEVENT,
	APPPACKETTYPE_SCTEXTOBJ,
	APPPACKETTYPE_SVRGOODBYEEVENT,
	APPPACKETTYPE_WINEVENT,
	APPPACKETTYPE_POWERUP,
	APPPACKETTYPE_STATIC,
	APPPACKETTYPE_DOOR,
	APPPACKETTYPE_ELEVATOR,
	APPPACKETTYPE_DSAPO,
	APPPACKETTYPE_SERVERFPS,
	APPPACKETTYPE_CONSOLECOMMANDEVENT,
	APPPACKETTYPE_RESETWINSEVENT,
	APPPACKETTYPE_EVICTIONEVENT,
	APPPACKETTYPE_NETWEATHER,
	APPPACKETTYPE_GAMEDATAUPDATEEVENT,
	APPPACKETTYPE_SCPINGRESPONSEEVENT,
	APPPACKETTYPE_BASECONTROLLER,
	APPPACKETTYPE_CINEMATIC,
	APPPACKETTYPE_C4,
	APPPACKETTYPE_BEACON,
	APPPACKETTYPE_SCEXPLOSIONEVENT,
	APPPACKETTYPE_SCOBELISKEVENT,
	APPPACKETTYPE_SCANNOUNCEMENT,
	APPPACKETTYPE_NETBACKGROUND,

	//
	// C->S
	//	
	APPPACKETTYPE_CLIENTCONTROL,
	APPPACKETTYPE_CSTEXTOBJ,
	APPPACKETTYPE_SUICIDEEVENT,
	APPPACKETTYPE_CHANGETEAMEVENT,
	APPPACKETTYPE_MONEYEVENT,
	APPPACKETTYPE_WARPEVENT,
	APPPACKETTYPE_PURCHASEREQUESTEVENT,
	APPPACKETTYPE_CLIENTGOODBYEEVENT,
	APPPACKETTYPE_BIOEVENT,
	APPPACKETTYPE_LOADINGEVENT,
	APPPACKETTYPE_GODMODEEVENT,
	APPPACKETTYPE_VIPMODEEVENT,
	APPPACKETTYPE_SCOREEVENT,
	APPPACKETTYPE_CLIENTBBOEVENT,
	APPPACKETTYPE_CLIENTFPS,
	APPPACKETTYPE_CSPINGREQUESTEVENT,
	APPPACKETTYPE_CSDAMAGEEVENT,
	APPPACKETTYPE_REQUESTKILLEVENT,
	APPPACKETTYPE_CSCONSOLECOMMANDEVENT,
	APPPACKETTYPE_CSHINT,
	APPPACKETTYPE_CSANNOUNCEMENT,
	APPPACKETTYPE_DONATEEVENT,

	//
	// Summation
	//
	APPPACKETTYPE_ALL,

	APPPACKETTYPE_COUNT,
};	

//-----------------------------------------------------------------------------


	//APPPACKETTYPE_FLAGCAPEVENT,
	//APPPACKETTYPE_STEALTHEVENT,
