#pragma once

#include "global.h"

////////////////////////////////////////////////////////////////
//	Network class IDs
////////////////////////////////////////////////////////////////
enum
{
	//
	// S-created objects
	//
	NETCLASSID_GAMEOBJ						= 1000,
	NETCLASSID_SCTEXTOBJ					= 1001,
	NETCLASSID_PLAYERKILL					= 1002,
	NETCLASSID_WIN							= 1003,
	NETCLASSID_PURCHASERESPONSEEVENT		= 1004,
	NETCLASSID_CONSOLECOMMANDEVENT			= 1005,
	NETCLASSID_RESETWINSEVENT				= 1006,
	NETCLASSID_SVRGOODBYEEVENT				= 1007,
	NETCLASSID_GAMEOPTIONSEVENT				= 1008,
	NETCLASSID_EVICTIONEVENT				= 1009,
	NETCLASSID_TEAM							= 1010,
	NETCLASSID_PLAYER						= 1011,
	NETCLASSID_GAMEDATAUPDATEEVENT			= 1012,
	NETCLASSID_SCPINGRESPONSEEVENT			= 1013,
	NETCLASSID_SCEXPLOSIONEVENT				= 1014,
	NETCLASSID_SCOBELISKEVENT				= 1015,
	NETCLASSID_SCANNOUNCEMENT				= 1016,
	NETCLASSID_GAMESPYSCCHALLENGEEVENT      = 1017,

	//
	// C-created objects
	//
	NETCLASSID_CLIENTCONTROL				= 1018,
	NETCLASSID_CSTEXTOBJ					= 1019,
	NETCLASSID_SUICIDEEVENT					= 1020,
	NETCLASSID_CHANGETEAMEVENT				= 1021,
	NETCLASSID_MONEYEVENT					= 1022,
	NETCLASSID_WARPEVENT					= 1023,
	NETCLASSID_PURCHASEREQUESTEVENT			= 1024,
	NETCLASSID_CLIENTGOODBYEEVENT			= 1025,
	NETCLASSID_BIOEVENT						= 1026,
	NETCLASSID_LOADINGEVENT					= 1027,
	NETCLASSID_GODMODEEVENT					= 1028,
	NETCLASSID_VIPMODEEVENT					= 1029,
	NETCLASSID_SCOREEVENT					= 1030,
	NETCLASSID_CLIENTBBOEVENT				= 1031,
	NETCLASSID_CLIENTFPS					= 1032,
	NETCLASSID_CSPINGREQUESTEVENT			= 1033,
	NETCLASSID_CSDAMAGEEVENT				= 1034,
	NETCLASSID_REQUESTKILLEVENT				= 1035,
	NETCLASSID_CSCONSOLECOMMANDEVENT		= 1036,
	NETCLASSID_CSHINT						= 1037,
	NETCLASSID_CSANNOUNCEMENT				= 1038,
	NETCLASSID_DONATEEVENT					= 1039,
};


	//NETCLASSID_MOBIUSCAPEVENT,
	//NETCLASSID_LMSPLAYEROUTEVENT,
	//NETCLASSID_MUTATIONEVENT,
	//NETCLASSID_LMSREAPEVENT,
	//NETCLASSID_SPECTATINGEVENT,
