#ifndef WWMATHIDS_H
#define WWMATHIDS_H

#include "saveloadids.h"

/*
** Persist Factory ID's for WWMATH
*/
enum 
{
	WWMATH_CHUNKID_LINEARCURVE1D	= CHUNKID_WWMATH_BEGIN,
	WWMATH_CHUNKID_HERMITESPLINE1D,
	WWMATH_CHUNKID_CATMULLROMSPLINE1D,
	WWMATH_CHUNKID_CARDINALSPLINE1D,
	WWMATH_CHUNKID_TCBSPLINE1D,

	WWMATH_CHUNKID_LINEARCURVE3D	= CHUNKID_WWMATH_BEGIN + 0x100,
	WWMATH_CHUNKID_HERMITESPLINE3D,
	WWMATH_CHUNKID_CATMULLROMSPLINE3D,
	WWMATH_CHUNKID_CARDINALSPLINE3D,
	WWMATH_CHUNKID_TCBSPLINE3D,
	WWMATH_CHUNKID_VEHICLECURVE
};



#endif //WWMATHIDS_H

