#if defined(_MSC_VER)
#pragma once
#endif

#ifndef __NODETYPES_H
#define __NODETYPES_H


///////////////////////////////////////////////////
//
//	Typedefs and structs
//
typedef enum
{
	NODE_TYPE_UNKNOWN = 0,
	NODE_TYPE_TERRAIN,
	NODE_TYPE_TERRAIN_SECTION,
	NODE_TYPE_TILE,
	NODE_TYPE_OBJECT,
	NODE_TYPE_ZONE,
	NODE_TYPE_WAYPATH,
	NODE_TYPE_WAYPOINT,
	NODE_TYPE_LIGHT,
	NODE_TYPE_TRANSITION,
	NODE_TYPE_TRANSITION_CHARACTER,
	NODE_TYPE_SOUND,
	NODE_TYPE_VIS,
	NODE_TYPE_SPAWNER,
	NODE_TYPE_VIS_POINT,
	NODE_TYPE_PATHFIND_START,
	NODE_TYPE_DUMMY_OBJECT,
	NODE_TYPE_COVER_SPOT,
	NODE_TYPE_COVER_ATTACK_POINT,
	NODE_TYPE_DAMAGE_ZONE,
	NODE_TYPE_BUILDING,
	NODE_TYPE_SPAWN_POINT,
	NODE_TYPE_BUILDING_CHILD_NODE,
	NODE_TYPE_EDITOR_ONLY_OBJ,
	NODE_TYPE_COUNT
} NODE_TYPE;


#endif //__NODETYPES_H
