#pragma once
// gamespyauthmgr.h stub - GameSpy authentication removed

enum GAMESPY_AUTH_STATE_ENUM {
    GAMESPY_AUTH_STATE_INITIAL = 0,
    GAMESPY_AUTH_STATE_AUTHENTICATED,
    GAMESPY_AUTH_STATE_FAILED,
    GAMESPY_AUTH_STATE_DISCONNECTED,
};

enum GAMESPY_KICK_STATE_ENUM {
    GAMESPY_KICK_STATE_INITIAL = 0,
    GAMESPY_KICK_STATE_NOT_KICKED = 0,
    GAMESPY_KICK_STATE_KICKED,
};
